server:
  port: 0

spring:
  application:
    name: notification-manager
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: root

logging:
  file: /tmp/notification-manager.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: Notification Manager
    description: Handle notifications
    version: ${version}

