INSERT INTO NOTIFICATION_TYPE ( TYPE, TYPE_DESCRIPTION) VALUES ('EMAIL', 'Envio de notificação de e-mail');
INSERT INTO NOTIFICATION_TYPE ( TYPE, TYPE_DESCRIPTION) VALUES ('SMS', 'Envio de notificação por SMS');
INSERT INTO NOTIFICATION_TYPE ( TYPE, TYPE_DESCRIPTION) VALUES ('PUSH', 'Envio de notificação por PUSH');
